// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace MyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231024071541_AddOrder")]
    partial class AddOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyApp.Model.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrdererAdd")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OrdererName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrdererTel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReceiverAdd")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiverTel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyApp.Model.OrderItem.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Product")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PetId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MyApp.Model.Pet.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Activity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyGrams")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IsNeutered")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetBreedId")
                        .HasColumnType("int");

                    b.Property<int?>("Posture")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PetBreedId");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("MyApp.Model.PetBreed.PetBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PetBreeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "千島短尾貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "土耳其安哥拉貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "土耳其梵貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "巴比諾貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "巴西短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "日本短尾貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "爪哇貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "加州閃亮貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "北美洲短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "卡特爾貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "尼比龍貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "尼亞貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "布偶貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "西伯利亞貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "伯曼貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "亞洲半長毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "亞洲貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "奇多貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "孟加拉貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "孟買貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "彼得禿貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "拉邦貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "東方長毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Name = "東方短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 25,
                            Name = "東方雙色貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 26,
                            Name = "東奇尼貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "波米拉貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 28,
                            Name = "波斯貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 29,
                            Name = "玩具虎貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 30,
                            Name = "肯尼亞貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 31,
                            Name = "俄勒岡捲毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            Name = "俄羅斯白貓、黑貓和虎斑貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 33,
                            Name = "俄羅斯藍貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 34,
                            Name = "哈瓦那棕貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 35,
                            Name = "威爾斯貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 36,
                            Name = "峇里貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 37,
                            Name = "查達利貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 38,
                            Name = "科拉特貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 39,
                            Name = "美國多趾貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 40,
                            Name = "美國短尾貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 41,
                            Name = "美國硬毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 42,
                            Name = "米克斯貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 43,
                            Name = "三色貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 44,
                            Name = "明斯欽貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            Name = "美國反耳貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 46,
                            Name = "美國短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 47,
                            Name = "約克巧克力貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 48,
                            Name = "英國長毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 49,
                            Name = "英國短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 50,
                            Name = "重點色短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 51,
                            Name = "埃及貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 52,
                            Name = "拿破崙貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 53,
                            Name = "挪威森林貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 54,
                            Name = "烏克蘭勒夫科伊貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 55,
                            Name = "烏蘇里貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 56,
                            Name = "狸花貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 57,
                            Name = "索馬利貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 58,
                            Name = "馬恩島貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 59,
                            Name = "康沃耳帝王貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 60,
                            Name = "曼切堪貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 61,
                            Name = "異國短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 62,
                            Name = "雪鞋貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 63,
                            Name = "喜馬拉雅貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 64,
                            Name = "斯芬克斯貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 65,
                            Name = "短毛家貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 66,
                            Name = "傳統暹羅貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 67,
                            Name = "塞倫蓋蒂貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 68,
                            Name = "塞浦路斯短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 69,
                            Name = "塞爾凱克鬈毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 70,
                            Name = "愛琴海貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 71,
                            Name = "新加坡貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 72,
                            Name = "獅子貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 73,
                            Name = "頓斯科伊貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 74,
                            Name = "德文帝王貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 75,
                            Name = "德國捲毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 76,
                            Name = "歐西貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 77,
                            Name = "歐洲短毛貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 78,
                            Name = "歐斯亞史烈斯貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 79,
                            Name = "熱帶草原貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 80,
                            Name = "緬因貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 81,
                            Name = "緬甸貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 82,
                            Name = "暹羅貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 83,
                            Name = "澳大利亞霧貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 84,
                            Name = "蘇格蘭摺耳貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 85,
                            Name = "襤褸貓",
                            Size = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 86,
                            Name = "哈士奇",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 87,
                            Name = "拉不拉多",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 88,
                            Name = "黃金獵犬",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 89,
                            Name = "鬆獅犬",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 90,
                            Name = "英國古代牧羊犬",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 91,
                            Name = "德國狼犬",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 92,
                            Name = "秋田犬",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 93,
                            Name = "聖伯納犬",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 94,
                            Name = "藏獒",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 95,
                            Name = "標準型貴賓",
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 96,
                            Name = "柴犬",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 97,
                            Name = "米克斯",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 98,
                            Name = "米格魯",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 99,
                            Name = "柯基",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 100,
                            Name = "台灣犬",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 101,
                            Name = "薩摩耶犬",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 102,
                            Name = "可卡",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 103,
                            Name = "邊境牧羊犬",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 104,
                            Name = "沙皮狗",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 105,
                            Name = "英國鬥牛犬",
                            Size = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 106,
                            Name = "吉娃娃",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 107,
                            Name = "約克夏",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 108,
                            Name = "博美",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 109,
                            Name = "瑪爾濟斯",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 110,
                            Name = "迷你貴賓犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 111,
                            Name = "迷你臘腸犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 112,
                            Name = "迷你雪納瑞",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 113,
                            Name = "西施",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 114,
                            Name = "巴哥犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 115,
                            Name = "狐狸犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 116,
                            Name = "法國鬥牛犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 117,
                            Name = "蝴蝶犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 118,
                            Name = "迷你杜賓犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 119,
                            Name = "比熊犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 120,
                            Name = "北京犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 121,
                            Name = "傑克羅素㹴",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 122,
                            Name = "鋼毛獵狐㹴",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 123,
                            Name = "喜樂蒂牧羊犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 124,
                            Name = "標準臘腸犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 125,
                            Name = "牛頭㹴",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 126,
                            Name = "標準雪納瑞",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 127,
                            Name = "杜賓犬",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 128,
                            Name = "西高地白㹴",
                            Size = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 129,
                            Name = "其他",
                            Size = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("MyApp.Model.User.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyApp.Model.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyApp.Model.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Model.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyApp.Model.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApp.Model.Order.Order", b =>
                {
                    b.HasOne("MyApp.Model.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Model.OrderItem.OrderItem", b =>
                {
                    b.HasOne("MyApp.Model.Order.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Model.Pet.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("MyApp.Model.Pet.Pet", b =>
                {
                    b.HasOne("MyApp.Model.PetBreed.PetBreed", "PetBreed")
                        .WithMany()
                        .HasForeignKey("PetBreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Model.User.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId");

                    b.Navigation("PetBreed");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Model.Order.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MyApp.Model.User.User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
